/**
 * Generates and downloads a markdown report from the resume analysis details.
 * @param {Object} analysis - The Gemini review analysis JSON object
 * @param {string} originalFileName - The name of the uploaded resume file
 */
export const downloadMarkdownReport = (analysis, originalFileName) => {
  if (!analysis) return;

  const {
    overallScore = 0,
    atsScore = 0,
    strengths = [],
    weaknesses = [],
    assessments = {},
    suggestions = {},
    roleAnalysis = {},
    actionPlan = [],
  } = analysis;

  const date = new Date().toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const mdText = `# AI RESUME REVIEW REPORT
Generated by CVSpark AI Resume Review Agent
Date: ${date}
Resume File: ${originalFileName || 'Uploaded Resume'}

================================================================================
OVERALL METRICS
================================================================================
* Overall Resume Score: ${overallScore} / 100
* ATS Compatibility Score: ${atsScore} / 100

================================================================================
STRENGTHS & WEAKNESSES
================================================================================
### Key Strengths:
${strengths.map(s => `- ${s}`).join('\n')}

### Areas for Improvement:
${weaknesses.map(w => `- ${w}`).join('\n')}

================================================================================
CORE ASSESSMENTS BREAKDOWN
================================================================================
### 1. Technical Skills Assessment (Score: ${assessments.technicalSkills?.score || 0}/100)
${assessments.technicalSkills?.review || 'No review available'}

### 2. Project Quality Assessment (Score: ${assessments.projectQuality?.score || 0}/100)
${assessments.projectQuality?.review || 'No review available'}

### 3. Education Assessment (Score: ${assessments.education?.score || 0}/100)
${assessments.education?.review || 'No review available'}

### 4. Certifications Assessment (Score: ${assessments.certifications?.score || 0}/100)
${assessments.certifications?.review || 'No review available'}

### 5. Formatting Assessment (Score: ${assessments.formatting?.score || 0}/100)
${assessments.formatting?.review || 'No review available'}

### 6. Grammar & Language Assessment (Score: ${assessments.grammar?.score || 0}/100)
${assessments.grammar?.review || 'No review available'}

### 7. Keyword Optimization Assessment (Score: ${assessments.keywordOptimization?.score || 0}/100)
${assessments.keywordOptimization?.review || 'No review available'}

================================================================================
AI REWRITE & EXPANSION SUGGESTIONS
================================================================================
### Recommended Missing Skills:
${suggestions.missingSkills?.join(', ') || 'None identified'}

### Recommended Target Keywords:
${suggestions.missingKeywords?.join(', ') || 'None identified'}

### Resume Improvement Tips:
${suggestions.improvements?.map(imp => `- ${imp}`).join('\n') || 'None'}

### Action Verb Enhancements:
${suggestions.actionVerbs?.map(v => `- Replace "${v.original}" with "${v.suggested}"`).join('\n') || 'None'}

### Suggested Career Summary / Objective:
"${suggestions.careerObjective || 'No suggestion available'}"

### Suggested Skills Section Structure:
\`\`\`
${suggestions.skillsSection || 'No structure available'}
\`\`\`

================================================================================
JOB ROLE SUITABILITY MATCHING
================================================================================
${Object.entries(roleAnalysis).map(([role, data]) => `
### Role: ${role}
- Suitability Match Score: ${data.matchScore}%
- Missing Skills for this Role: ${data.missingSkills?.join(', ') || 'None'}
- Suitability Guidance:
  ${data.recommendations?.map(rec => `  * ${rec}`).join('\n') || '  * Match quality high.'}
`).join('\n')}

================================================================================
PRIORITY ACTION PLAN
================================================================================
${actionPlan.map((p) => `${p.priority || '#'}. [${p.impact} Impact] ${p.action}
   Recommendation: ${p.description}`).join('\n\n')}

================================================================================
REPORT END
================================================================================
`;

  // Create blob and download
  const blob = new Blob([mdText], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  
  const formattedFileName = (originalFileName || 'resume')
    .toLowerCase()
    .replace(/\.pdf$/, '')
    .replace(/[^a-z0-9]+/g, '-');
    
  link.href = url;
  link.setAttribute('download', `${formattedFileName}-review-report.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
